"""Self-evolving agent simulation.

This module simulates an autorewriting neural-style agent that:
- keeps a persistent identity and history
- mutates itself when performance fails to improve
- justifies its updates in a structured log

It does not claim to solve open mathematical problems; it provides
numerical experimentation and a self-optimization loop for education.
"""

from __future__ import annotations

import argparse
import json
import math
import random
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List


def _now() -> float:
    return time.time()


@dataclass
class AgentState:
    agent_id: str
    created_at: float
    version: int
    best_score: float
    mutation_scale: float
    weights: List[float]
    history: List[Dict[str, object]] = field(default_factory=list)

    @classmethod
    def initial(cls, num_weights: int, seed: int | None = None) -> "AgentState":
        rng = random.Random(seed)
        weights = [rng.uniform(-1.0, 1.0) for _ in range(num_weights)]
        return cls(
            agent_id=str(uuid.uuid4()),
            created_at=_now(),
            version=0,
            best_score=-math.inf,
            mutation_scale=0.5,
            weights=weights,
            history=[],
        )

    def record(self, entry: Dict[str, object]) -> None:
        self.history.append(entry)


class SelfEvolvingAgent:
    def __init__(self, state: AgentState, policy_path: Path) -> None:
        self.state = state
        self.policy_path = policy_path

    def evaluate(self, target: List[float]) -> float:
        loss = sum((w - t) ** 2 for w, t in zip(self.state.weights, target))
        return -loss

    def propose_mutation(self) -> List[float]:
        return [
            w + random.gauss(0.0, self.state.mutation_scale)
            for w in self.state.weights
        ]

    def justify(self, improved: bool, score: float, target: List[float]) -> Dict[str, object]:
        rationale = (
            "Improvement detected; consolidating change and narrowing search."
            if improved
            else "No improvement; widening exploration to escape local minima."
        )
        return {
            "timestamp": _now(),
            "version": self.state.version,
            "score": score,
            "mutation_scale": self.state.mutation_scale,
            "target_norm": math.sqrt(sum(t ** 2 for t in target)),
            "rationale": rationale,
        }

    def update_policy_file(self) -> None:
        weights_literal = repr(self.state.weights)
        content = f'''"""Autogenerated policy module for the self-evolving agent."""
import math

WEIGHTS = {weights_literal}


def policy(inputs):
    """Return a dot-product score for the given inputs."""
    return sum(w * x for w, x in zip(WEIGHTS, inputs))
'''
        self.policy_path.write_text(content)

    def step(self, target: List[float]) -> Dict[str, object]:
        proposed = self.propose_mutation()
        original = list(self.state.weights)

        original_score = self.evaluate(target)
        self.state.weights = proposed
        candidate_score = self.evaluate(target)

        improved = candidate_score > original_score
        if improved:
            self.state.best_score = max(self.state.best_score, candidate_score)
            self.state.mutation_scale = max(self.state.mutation_scale * 0.9, 0.05)
            action = "accepted"
        else:
            self.state.weights = original
            self.state.mutation_scale = min(self.state.mutation_scale * 1.1, 2.0)
            action = "rejected"

        self.state.version += 1
        justification = self.justify(improved, candidate_score, target)
        justification.update(
            {
                "action": action,
                "best_score": self.state.best_score,
                "agent_id": self.state.agent_id,
            }
        )
        self.state.record(justification)
        self.update_policy_file()
        return justification


def load_state(path: Path, num_weights: int, seed: int | None) -> AgentState:
    if not path.exists():
        return AgentState.initial(num_weights=num_weights, seed=seed)
    data = json.loads(path.read_text())
    return AgentState(
        agent_id=data["agent_id"],
        created_at=data["created_at"],
        version=data["version"],
        best_score=data["best_score"],
        mutation_scale=data["mutation_scale"],
        weights=data["weights"],
        history=data.get("history", []),
    )


def save_state(path: Path, state: AgentState) -> None:
    payload = {
        "agent_id": state.agent_id,
        "created_at": state.created_at,
        "version": state.version,
        "best_score": state.best_score,
        "mutation_scale": state.mutation_scale,
        "weights": state.weights,
        "history": state.history,
    }
    path.write_text(json.dumps(payload, indent=2))


def parse_target(values: str, num_weights: int) -> List[float]:
    parts = [float(part.strip()) for part in values.split(",") if part.strip()]
    if len(parts) != num_weights:
        raise ValueError(
            f"Expected {num_weights} target values, received {len(parts)}."
        )
    return parts


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run a self-evolving agent that rewrites its own policy file."
    )
    parser.add_argument("--steps", type=int, default=10, help="Number of evolution steps")
    parser.add_argument("--weights", type=int, default=6, help="Number of weights")
    parser.add_argument("--seed", type=int, default=None, help="Seed for reproducibility")
    parser.add_argument(
        "--target",
        type=str,
        default=None,
        help="Comma-separated target vector (defaults to random)",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=Path("autonomous_agent"),
        help="Output directory for state and policy",
    )
    args = parser.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    state_path = args.outdir / "agent_state.json"
    policy_path = args.outdir / "agent_policy.py"

    state = load_state(state_path, num_weights=args.weights, seed=args.seed)

    if args.target is None:
        rng = random.Random(args.seed)
        target = [rng.uniform(-1.0, 1.0) for _ in range(args.weights)]
    else:
        target = parse_target(args.target, args.weights)

    agent = SelfEvolvingAgent(state=state, policy_path=policy_path)

    for _ in range(args.steps):
        result = agent.step(target)
        summary = (
            f"v{result['version']} | {result['action']} | "
            f"score={result['score']:.4f} | mutation={result['mutation_scale']:.3f}"
        )
        print(summary)
        print(f"Justification: {result['rationale']}")

    save_state(state_path, agent.state)


if __name__ == "__main__":
    main()
